SELECT PRODUCT_CODE, CNT*PRICE AS SALES
FROM (
    SELECT P.PRODUCT_CODE, SUM(SALES_AMOUNT) AS CNT, PRICE
    FROM PRODUCT P INNER JOIN OFFLINE_SALE OS ON P.PRODUCT_ID = OS.PRODUCT_ID
    GROUP BY P.PRODUCT_CODE) A
ORDER BY SALES DESC, PRODUCT_CODE ASC

    # SELECT  *
    # SELECT P.PRODUCT_CODE, COUNT(SALES_AMOUNT) AS CNT, PRICE
    # FROM PRODUCT P JOIN OFFLINE_SALE OS ON P.PRODUCT_ID = OS.PRODUCT_ID
    # GROUP BY P.PRODUCT_CODE