SELECT HISTORY_ID, FLOOR(DAILY_FEE*(1-IFNULL(DISCOUNT_RATE,0)*0.01)*(DATEDIFF(END_DATE, START_DATE)+1)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID=H.CAR_ID AND C.CAR_TYPE ='트럭' LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON B.CAR_TYPE='트럭'
AND ((DATEDIFF(END_DATE, START_DATE)+1 >= 90 && DURATION_TYPE='90일 이상') OR
(DATEDIFF(END_DATE, START_DATE)+1 >= 30 && DATEDIFF(END_DATE, START_DATE)+1 < 90 && DURATION_TYPE='30일 이상') OR
(DATEDIFF(END_DATE, START_DATE)+1 >= 7 && DATEDIFF(END_DATE, START_DATE)+1 < 30 && DURATION_TYPE='7일 이상'))
ORDER BY FEE DESC, HISTORY_ID DESC

# 7일 미만는 계산이 안됨