# 리뷰를 가장 많이 작성한 회원 찾기
# 그 회원의 리뷰조회 

# 1. 회원들의 리뷰 작성 개수 세기
# SELECT *, COUNT(*) AS COUNT
# FROM  REST_REVIEW
# GROUP BY MEMBER_ID 
# ORDER BY COUNT

# 2. 가장 많이 작성한 회원 알아내기
# SELECT MEMBER_ID
# FROM
# (SELECT *, COUNT(*) AS COUNT
# FROM  REST_REVIEW
# GROUP BY MEMBER_ID 
# ) MR
# WHERE MR.COUNT = (
#     SELECT MAX(COUNT) AS MAX_COUNT
#     FROM (
#     SELECT *, COUNT(*) AS COUNT
#     FROM  REST_REVIEW
#     GROUP BY MEMBER_ID ) MR)
    
# 3. 2의 회원들의 리뷰 출력하기
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (
    MEMBER_PROFILE m JOIN REST_REVIEW r 
    ON m.MEMBER_ID = r.MEMBER_ID)
WHERE m.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM
    (SELECT *, COUNT(*) AS COUNT
    FROM  REST_REVIEW
    GROUP BY MEMBER_ID 
    ) MR
    WHERE MR.COUNT = (
        SELECT MAX(COUNT) AS MAX_COUNT
        FROM (
        SELECT *, COUNT(*) AS COUNT
        FROM  REST_REVIEW
        GROUP BY MEMBER_ID ) MR)
)
ORDER BY REVIEW_DATE, REVIEW_TEXT
# SELECT *
# FROM (
#     MEMBER_PROFILE m JOIN REST_REVIEW r ON m.MEMBER_ID = r.MEMBER_ID ) 