SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT *
    FROM FISH_INFO FI
    WHERE (FI.FISH_TYPE, FI.LENGTH) IN
            (
                SELECT FISH_TYPE, MAX(LENGTH)
                FROM FISH_INFO
                GROUP BY FISH_TYPE
            )
) A INNER JOIN FISH_NAME_INFO B ON A.FISH_TYPE=B.FISH_TYPE